name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake checks (build validation)
        run: nix flake check --show-trace

      - name: Build home-manager configuration
        run: nix build .#homeConfigurations.reinoud.activationPackage

      - name: Activate home-manager in test environment
        run: |
          export HOME=$(mktemp -d)
          ./result/activate

      - name: Install Python and pexpect for tests
        run: |
          nix-shell -p python3 python3Packages.pexpect --run "python3 tests/integration/test_shell.py"
